function zhelp --description "Print a quick reference of useful zellij keybindings"
    echo "── Zellij quick reference ─────────────────────────────"
    echo "Ctrl-p n       New tab"
    echo "Ctrl-p x       Close tab"
    echo "Ctrl-p r       Rename tab"
    echo "Ctrl-p →/←     Next/previous tab"
    echo "Ctrl-p 1-9     Jump to tab by number"
    echo ""
    echo "Ctrl-n         Resize mode"
    echo "Ctrl-p         Pane mode"
    echo "Ctrl-t         Tab mode"
    echo "Ctrl-o         Session mode"
    echo ""
    echo "Ctrl-p d       Detach session"
    echo "Ctrl-p s       New pane (horizontal split)"
    echo "Ctrl-p v       New pane (vertical split)"
    echo "Ctrl-p z       Toggle pane zoom"
    echo "────────────────────────────────────────────────────────"
end
